input_size:
  height: 32
  width: 32
  depth: 3

optimizer:
  name: adam

initial_learning_rate: 1e-4

training_param:
  batch_size: 1
  num_epochs_phase1: 1
  num_epochs_phase2: 2
  test_size: 0.2

encoder_path: le.pickle
output_plot_path: plot.png

real_face_path: ./dataset/real
fake_face_path: ./dataset/fake
model_path: ./liveness_model

debugging: True